repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: pyanalyze
        name: pyanalyze
        entry: python3.11 -m pyanalyze --config-file pyproject.toml
        language: python
        files: ^(clorm|tests)/.*\.py$
        additional_dependencies:
          - pyanalyze>=0.10.1
